site_name: "M√≥dulo 7 SI üñ•Ô∏è"
site_description: "Documenta√ß√£o do M√≥dulo 7 de Sistemas de Informa√ß√£o"
site_author: "Afonso Brand√£o"
theme:
  name: "mkdocs"
nav:
  - Home: index.md
  - Aulas:
      - "Regras de neg√≥cio e tomada de decis√£o": 01regras.md
      - "Avalia√ß√£o e sele√ß√£o de sistemas de informa√ß√£o": 02avaliacao.md
      - "Testes e cutover no contexto de sistemas empresariais": 03cutover.md
      - "Gest√£o de mudan√ßas": 04mudanca.md
      - "Governan√ßa corporativa e de dados": 05govdados.md
      - "Gest√£o de Stakeholders": 06stakeholders.md
      - "Implanta√ß√£o de sistemas": 07impsis.md
      - "Estrat√©gia e gest√£o de servi√ßos de TI": 08estrategia.md
      - "Elabora√ß√£o de relat√≥rios": 09relatorios.md
      - "Sistemas distribu√≠dos": 10sisdis.md
      - "Seguran√ßa em Sistemas distribu√≠dos": 11segdis.md
